### ISSUE TITLE
Targets Mono?

### ISSUE THREAD

**Issue by tekhedd** [MediaBrowser/SocketHttpListener#10]
Only a 4.5 binary is available via Nuget so I attempted to build with mcs 4.0.4.0. Socket does not contain a definition for DualMode... Project no longer supports/targets Mono?

Could not find the tags from which nuget releases are built...is this normal?

**Comment by LukePulverenti** [comment]
i didn't realize, thanks. i guess we'll need a separate 4.0 binary then.

**Comment by tekhedd** [comment]
Cool! Of course the question will be whether DualMode is going to be an issue but I haven't looked that deep into the code so I have no idea. :)

I'll put together a PR with conditional compile for the DualMode support added in 4.5.

**Comment by tekhedd** [comment]
Mono project added the DualMode property in april... not sure why it is unavailable in the 4.0.4 release. Possibly mcs defaulting to the 4.0 runtime (but that's weird when xbuild specifies 4.5). Suspect this is going to turn into a "never mind no action necessary" item. Investigating.

**Comment by tekhedd** [comment]
It's fixed in mono 4.2, still in alpha. As I am the only one who has even noticed this issue, I recommend that people who need DualMode stick to the 1.0.0.10 release until mono 4.2 is officially released, and call it good.

**Comment by tekhedd** [comment]
Yes. I can confirm that the current NuGet build works with mono 4.2. Use 1.0.0.10 or wait for mono 4.2. Thanks much.
