### ISSUE TITLE
Could not load type 'NullLogger'

### ISSUE THREAD

**Issue by slothbag** [MediaBrowser/SocketHttpListener#11]
I just tried switching from Mono.HttpListener to this library, I had to update my Mono installation to the latest version (not a big issue).

The app now crashes with error 

```
Could not load type 'NullLogger' from assembly 'Patterns.Logging.dll'.
```

I'm on latest Ubuntu Linux.  I added the SocketHttpListener via Nuget

**Comment by LukePulverenti** [comment]
That dependency is listed in the nuget package, so you probably just need to restore it from nuget.

**Comment by slothbag** [comment]
I can see the Pattern.Logging dependency was downloaded into the packages folder, and it is also in the build output folder along with the exe.

**Comment by LukePulverenti** [comment]
I built it all targeting .net 4.5 so if you're trying to target anything lower then that could be an issue. That's all i can think of.

**Comment by slothbag** [comment]
Yeah i'm on 4.5.  When I get a chance i'll add the source code and try compile in manually. Thanks for taking a look.

**Comment by WJ-GitHub** [comment]
Had same problem that could be solved by removing mono-complete by apt-get and reinstalling using their webpage: http://www.mono-project.com/docs/getting-started/install/linux/
